version: '3.9'

services:

  explorer:
    build:
      context: ./Backend/
      target: final
    networks:
      - database
    ports:
      - "44333:80"
    restart: on-failure
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5433
      DATABASE_PASSWORD: super
      DATABASE_USER: postgres
      DATABASE_SCHEMA: explorer
      GO_TOUR_SERVICE_HOST: go-tour-service
      GO_ENCOUNTERS_SERVICE_HOST: go-encounter-service
    depends_on:
      - db
      - go-tour-service
      - go-encounter-service

  go-encounter-service:
    build:
      context: ./Encounters/
    ports:
      - "8090:8090"
    restart: on-failure
    networks:
      - database
    depends_on:
      - db
    environment:
      - DATABASE_URL=host=db user=postgres password=super dbname=encountersdb port=5433 sslmode=disable

  go-tour-service:
    build:
      context: ./Tours/
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - database
    environment:
      # protocol://username:password@hostname:port
      - MONGO_DB_URI=mongodb://root:pass@mongo:27017
      # - MONGO_DB_URI=mongodb://mongo:27017
    depends_on:
      mongo:
        condition: service_healthy


  db:
    image: postgres:latest
    restart: always
    networks:
      - database
    ports:
      - "5433:5433"
    volumes:
      - ./db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
      - type: bind
        source: explorer-init-data.sql
        target: /tmp/explorer-init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
      POSTGRES_MULTIPLE_DATABASES: tourdb,explorer,encountersdb
      PGPORT: 5433

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoDemo
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_store:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    volumes:
      - mongo_express_data:/data/db

volumes:
  mongo_store:
  mongo_express_data:

networks:
  database:
    name: database
    driver: bridge
