// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: tours/tours-service.proto

package tours

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TourKeypointIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TourKeypointIdRequest) Reset() {
	*x = TourKeypointIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tours_tours_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TourKeypointIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourKeypointIdRequest) ProtoMessage() {}

func (x *TourKeypointIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourKeypointIdRequest.ProtoReflect.Descriptor instead.
func (*TourKeypointIdRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{0}
}

func (x *TourKeypointIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TourKeypoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name           string  `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description    string  `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Image          string  `protobuf:"bytes,4,opt,name=Image,proto3" json:"Image,omitempty"`
	Latitude       float64 `protobuf:"fixed64,5,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude      float64 `protobuf:"fixed64,6,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	TourId         int32   `protobuf:"varint,7,opt,name=TourId,proto3" json:"TourId,omitempty"`
	Secret         string  `protobuf:"bytes,8,opt,name=Secret,proto3" json:"Secret,omitempty"`
	PositionInTour int32   `protobuf:"varint,9,opt,name=PositionInTour,proto3" json:"PositionInTour,omitempty"`
	PublicPointId  int32   `protobuf:"varint,10,opt,name=PublicPointId,proto3" json:"PublicPointId,omitempty"`
}

func (x *TourKeypoint) Reset() {
	*x = TourKeypoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tours_tours_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TourKeypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourKeypoint) ProtoMessage() {}

func (x *TourKeypoint) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourKeypoint.ProtoReflect.Descriptor instead.
func (*TourKeypoint) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{1}
}

func (x *TourKeypoint) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourKeypoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TourKeypoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TourKeypoint) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *TourKeypoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *TourKeypoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *TourKeypoint) GetTourId() int32 {
	if x != nil {
		return x.TourId
	}
	return 0
}

func (x *TourKeypoint) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *TourKeypoint) GetPositionInTour() int32 {
	if x != nil {
		return x.PositionInTour
	}
	return 0
}

func (x *TourKeypoint) GetPublicPointId() int32 {
	if x != nil {
		return x.PublicPointId
	}
	return 0
}

type EmptyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tours_tours_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{2}
}

var File_tours_tours_service_proto protoreflect.FileDescriptor

var file_tours_tours_service_proto_rawDesc = []byte{
	0x0a, 0x19, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x2f, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x15, 0x54,
	0x6f, 0x75, 0x72, 0x4b, 0x65, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x22, 0xa2, 0x02, 0x0a, 0x0c, 0x54, 0x6f, 0x75, 0x72, 0x4b, 0x65, 0x79,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x54,
	0x6f, 0x75, 0x72, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x54, 0x6f, 0x75,
	0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x54, 0x6f, 0x75, 0x72, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x54,
	0x6f, 0x75, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xbd, 0x01, 0x0a, 0x0b, 0x54,
	0x6f, 0x75, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x03, 0x47, 0x65,
	0x74, 0x12, 0x16, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x4b, 0x65, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x54, 0x6f, 0x75, 0x72,
	0x4b, 0x65, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x0d, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x4b, 0x65, 0x79, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x1a, 0x0d, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x4b, 0x65, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x26, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x54, 0x6f, 0x75,
	0x72, 0x4b, 0x65, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x1a, 0x0d, 0x2e, 0x54, 0x6f, 0x75, 0x72,
	0x4b, 0x65, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x16, 0x2e, 0x54, 0x6f, 0x75, 0x72, 0x4b, 0x65, 0x79, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_tours_tours_service_proto_rawDescOnce sync.Once
	file_tours_tours_service_proto_rawDescData = file_tours_tours_service_proto_rawDesc
)

func file_tours_tours_service_proto_rawDescGZIP() []byte {
	file_tours_tours_service_proto_rawDescOnce.Do(func() {
		file_tours_tours_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_tours_tours_service_proto_rawDescData)
	})
	return file_tours_tours_service_proto_rawDescData
}

var file_tours_tours_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tours_tours_service_proto_goTypes = []interface{}{
	(*TourKeypointIdRequest)(nil), // 0: TourKeypointIdRequest
	(*TourKeypoint)(nil),          // 1: TourKeypoint
	(*EmptyResponse)(nil),         // 2: EmptyResponse
}
var file_tours_tours_service_proto_depIdxs = []int32{
	0, // 0: TourService.Get:input_type -> TourKeypointIdRequest
	1, // 1: TourService.Create:input_type -> TourKeypoint
	1, // 2: TourService.Update:input_type -> TourKeypoint
	0, // 3: TourService.Delete:input_type -> TourKeypointIdRequest
	1, // 4: TourService.Get:output_type -> TourKeypoint
	1, // 5: TourService.Create:output_type -> TourKeypoint
	1, // 6: TourService.Update:output_type -> TourKeypoint
	2, // 7: TourService.Delete:output_type -> EmptyResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tours_tours_service_proto_init() }
func file_tours_tours_service_proto_init() {
	if File_tours_tours_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tours_tours_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TourKeypointIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tours_tours_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TourKeypoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tours_tours_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tours_tours_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tours_tours_service_proto_goTypes,
		DependencyIndexes: file_tours_tours_service_proto_depIdxs,
		MessageInfos:      file_tours_tours_service_proto_msgTypes,
	}.Build()
	File_tours_tours_service_proto = out.File
	file_tours_tours_service_proto_rawDesc = nil
	file_tours_tours_service_proto_goTypes = nil
	file_tours_tours_service_proto_depIdxs = nil
}
