services:
  loki:
    image: grafana/loki:latest
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3030:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    networks:
      - monitoring

  renderer:
    image: grafana/grafana-image-renderer:latest
    environment:
      - ENABLE_METRICS="true"
    networks:
      - monitoring

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:latest
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring
