version: "3.7"
services:
  servers:
    build:
      context: ./
      dockerfile: Dockerfile
    image: encounters_microservice
    container_name: encounters
    restart: always
    networks:
      - servers
    ports:
      - 8090:8090
    depends_on:
      - database
  
  database:
    image: postgres:13
    container_name: encounters_db
    restart: always
    networks:
      - servers
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
      POSTGRES_DB: encountersdb
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
    name: server-database

networks:
  servers:
    name: servers
    driver: bridge