version: "3.7"
services:
  servers:
    build:
      context: ./
      dockerfile: Dockerfile
    image: tours_microservice
    container_name: tours
    restart: always
    networks:
      - servers
    ports:
      - 8080:8080
    depends_on:
      - database
  
  database:
    image: postgres:13
    container_name: tours_db
    restart: always
    networks:
      - servers
    ports:
      - 4000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
      POSTGRES_DB: tourdb
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
    name: server-database

networks:
  servers:
    name: servers
    driver: bridge