// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: tour-service/tour-service.proto

package tour_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TourService_Get_FullMethodName    = "/TourService/Get"
	TourService_Create_FullMethodName = "/TourService/Create"
	TourService_Update_FullMethodName = "/TourService/Update"
	TourService_Delete_FullMethodName = "/TourService/Delete"
)

// TourServiceClient is the client API for TourService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourServiceClient interface {
	Get(ctx context.Context, in *TourKeypointIdRequest, opts ...grpc.CallOption) (*TourKeypoint, error)
	Create(ctx context.Context, in *TourKeypoint, opts ...grpc.CallOption) (*TourKeypoint, error)
	Update(ctx context.Context, in *TourKeypoint, opts ...grpc.CallOption) (*TourKeypoint, error)
	Delete(ctx context.Context, in *TourKeypointIdRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type tourServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourServiceClient(cc grpc.ClientConnInterface) TourServiceClient {
	return &tourServiceClient{cc}
}

func (c *tourServiceClient) Get(ctx context.Context, in *TourKeypointIdRequest, opts ...grpc.CallOption) (*TourKeypoint, error) {
	out := new(TourKeypoint)
	err := c.cc.Invoke(ctx, TourService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) Create(ctx context.Context, in *TourKeypoint, opts ...grpc.CallOption) (*TourKeypoint, error) {
	out := new(TourKeypoint)
	err := c.cc.Invoke(ctx, TourService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) Update(ctx context.Context, in *TourKeypoint, opts ...grpc.CallOption) (*TourKeypoint, error) {
	out := new(TourKeypoint)
	err := c.cc.Invoke(ctx, TourService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) Delete(ctx context.Context, in *TourKeypointIdRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, TourService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourServiceServer is the server API for TourService service.
// All implementations must embed UnimplementedTourServiceServer
// for forward compatibility
type TourServiceServer interface {
	Get(context.Context, *TourKeypointIdRequest) (*TourKeypoint, error)
	Create(context.Context, *TourKeypoint) (*TourKeypoint, error)
	Update(context.Context, *TourKeypoint) (*TourKeypoint, error)
	Delete(context.Context, *TourKeypointIdRequest) (*EmptyResponse, error)
	mustEmbedUnimplementedTourServiceServer()
}

// UnimplementedTourServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTourServiceServer struct {
}

func (UnimplementedTourServiceServer) Get(context.Context, *TourKeypointIdRequest) (*TourKeypoint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTourServiceServer) Create(context.Context, *TourKeypoint) (*TourKeypoint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTourServiceServer) Update(context.Context, *TourKeypoint) (*TourKeypoint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedTourServiceServer) Delete(context.Context, *TourKeypointIdRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTourServiceServer) mustEmbedUnimplementedTourServiceServer() {}

// UnsafeTourServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourServiceServer will
// result in compilation errors.
type UnsafeTourServiceServer interface {
	mustEmbedUnimplementedTourServiceServer()
}

func RegisterTourServiceServer(s grpc.ServiceRegistrar, srv TourServiceServer) {
	s.RegisterService(&TourService_ServiceDesc, srv)
}

func _TourService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourKeypointIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).Get(ctx, req.(*TourKeypointIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourKeypoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).Create(ctx, req.(*TourKeypoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourKeypoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).Update(ctx, req.(*TourKeypoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourKeypointIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).Delete(ctx, req.(*TourKeypointIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TourService_ServiceDesc is the grpc.ServiceDesc for TourService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TourService",
	HandlerType: (*TourServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _TourService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _TourService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TourService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TourService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tour-service/tour-service.proto",
}
